spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walkbook?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: pe1596357
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      database:0
      host:127.0.0.1
      port:6379
  activemq:
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
  jms:
    topic-name: topic
    queue-name: queue
mybatis:
  mapper-locations: classpath*:mapper/*.xml

